#!/usr/bin/env bash
set -e

type -p brew >/dev/null || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

for file in "$PWD"/*; do
  name="$(basename "$file" .md)"
  [[ $name = bin ]] && dotname="$name" || dotname=".${name}"

  [[ "README script vscode fonts" =~ $name ]] && continue

  ln -sfnv ${file#$HOME/} "${HOME}/${dotname}"
done

brew bundle --global --no-upgrade

# Install nvm
command -v nvm >/dev/null || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh)"

./script/install_code_extensions

# set screenshots folder
mkdir -p ~/Pictures/screenshots
defaults write com.apple.screencapture location ~/Pictures/screenshots

fonts/install.sh

echo "Done!"

